####################################################################
# release-manager.flow.yml
####################################################################
# Ragdata's Release Manager Workflow
#
# File:         release-manager.flow.yml
# Version:      1.0
# Author:       Ragdata
# Date:         27/07/2024
# License:      MIT License
# Copyright:    Copyright © 2024 Redeyed Technologies
####################################################################
name: Ragdata's Release Manager

on:
    # Allows for manual triggering via the Actions tab
    workflow-dispatch:
        inputs:
            version:
                description: "Release version"
                required: false
                type: string
            type:
                description: "Bump Type (patch/minor/major)"
                required: false
                type: string
        secrets:
            token:
                required: true

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:

    release_manager:
        name: Release Manager
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:

            ########################################################
            # Checkout Repository
            ########################################################
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            ########################################################
            # Transcribe Input Variables to ENV
            ########################################################
            # Specific Release Version
            - name: VERSION
              if: ${{ inputs.version }}
              run: echo "RELEASE_VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"

            # Desired Bump Type
            - name: TYPE
              if: ${{ inputs.type }}
              run: echo "BUMP_TYPE=${{ inputs.type }}" >> "$GITHUB_ENV"

            ########################################################
            # Manage Release
            ########################################################
            - name: Manage Release
              uses: ragdata/release-manager-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
