####################################################################
# .mega-linter.yml
####################################################################
# MegaLinter Configuration File
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
    - ACTION_ACTIONLINT
    - ANSIBLE_ANSIBLE_LINT
    - BASH_EXEC
    - BASH_SHELLCHECK
    - DOCKERFILE_HADOLINT
    - ENV_DOTENV_LINTER
    - HTML_HTMLHINT
    - JAVASCRIPT_STANDARD
    - JSON_JSONLINT
    - MARKDOWN_MARKDOWNLINT
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_PHPSTAN
    - POWERSHELL_POWERSHELL
    - PYTHON_PYLINT
    - REPOSITORY_GITLEAKS
    - REPOSITORY_TRIVY
    - RUBY_RUBOCOP
    - SPELL_PROSELINT
    - SQL_SQL_LINT
    - TYPESCRIPT_STANDARD
    - XML_XMLLINT
    - YAML_YAMLLINT
# DISABLE: If you use DISABLE variable, the linters in the listed descriptors will be skipped
# DISABLE_LINTERS: # If you use DISABLE_LINTERS variable, the listed linters will be skipped
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: (\.automation|\.idea|\.vscode|\.venv)
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3008"
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: true
REPOSITORY_TRIVY_CONFIG_FILE: .trivy.yml
